name: py-js
options:
  bundleIdPrefix: org.me
settings:
  MACOSX_DEPLOYMENT_TARGET: "10.13"
  CODE_SIGN_IDENTITY: "-"
  DEVELOPMENT_TEAM: ""
  GCC_OPTIMIZATION_LEVEL: z
  GCC_NO_COMMON_BLOCKS: No
  HEADER_SEARCH_PATHS:
    - $(C74SUPPORT)/max-includes
    - $(C74SUPPORT)/msp-includes
    - $(C74SUPPORT)/jit-includes
    - $(PROJECT_HEADERS)
  INFOPLIST_FILE: $(SRCROOT)/../../../Info.plist
  LIBRARY_SEARCH_PATHS: $(PROJECT_LIBS)
  OTHER_LDFLAGS:
    - $(C74_SYM_LINKER_FLAGS)
    - $(MSP_JIT_LDFLAGS)
    - $(PROJECT_LDFLAGS)
  PRODUCT_NAME: $(TARGET_NAME)
  BUILD_LIBRARY_FOR_DISTRIBUTION: yes
  ASSETCATALOG_COMPILER_OPTIMIZATION: space
  DEAD_CODE_STRIPPING: yes
  CONFIGURATION: Release
  DEPLOYMENT_POSTPROCESSING: yes
  STRIP_INSTALLED_PRODUCT: yes
  COPY_PHASE_STRIP: yes
  # FRAMEWORK_SEARCH_PATHS
configFiles:
  Debug: project.xcconfig
  Release: project.xcconfig

targets:
  py:
    type: bundle
    platform: macOS
    sources:
      - ../../py.c
      - ../../api.c
    dependencies:
      - sdk: CoreFoundation.framework
      - framework: ../build/lib/Python.framework
        embed: true
        copy:
          destination: resources

  pyjs:
    type: bundle
    platform: macOS
    sources:
      - ../../pyjs.c
    dependencies:
      - sdk: CoreFoundation.framework
      - framework: ../build/lib/Python.framework
        embed: true
        copy:
          destination: resources
