name: pyjs-framework-ext

on:
  workflow_dispatch:

env:
  variant: framework-ext
  arch: darwin-x86

jobs:
  build:
    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        fetch-depth: '0'

    - name: cache downloads
      id: cache-downloads
      uses: actions/cache@v3
      env:
        cache-name: pyjs-cache-1
      with:
        path: |
          source/py/targets/build/downloads
          source/py/targets/build/lib/bzip2
          source/py/targets/build/lib/openssl
          source/py/targets/build/lib/xz
        key: $${{ env.cache-name }}-${{ hashFiles('source/py/resources/pyjs-dependencies.txt') }}

    - name: Build externals
      run: make ${{ env.variant }}
